import { ArrowLeftOnRectangleIcon } from "@heroicons/react/24/outline";
import moment from "moment";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Header } from "../components/common/Header/Header";

function AccountPage() {
  moment.locale("es");
  const router = useRouter();
  const { data: session, status } = useSession();

  useEffect(() => {
    if (status === "unauthenticated") {
      void router.push("/login");
    }
  }, [status]);
  const userName = session?.user?.name;
  const userImage = session?.user?.image;
  const userEmail = session?.user?.email;
  const userSessionExpiresIn = moment().to(session?.expires);
  return (
    <>
      <Head>
        <title>Comodo Stock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-auto max-w-xl px-16 pb-10">
        {session && (
          <li className="flex max-w-sm cursor-default flex-col gap-4 overflow-hidden rounded bg-gray-300 shadow-xl dark:bg-gray-700 dark:text-gray-400">
            <Image
              height={700}
              width={700}
              className="rounded-t-md"
              src={userImage!}
              alt="profile picture"
            />
            <section className="flex flex-col px-4">
              <label className="text-sm text-gray-500 dark:text-gray-400 md:text-lg">
                Nombre de usuario
              </label>
              <span className="mb-2 cursor-pointer text-lg font-bold text-gray-700 dark:text-gray-100">
                {userName}
              </span>
              <label className="text-sm text-gray-500 dark:text-gray-400 md:text-lg">
                Email
              </label>

              <span className="mb-2 cursor-pointer text-lg font-bold text-gray-700 dark:text-gray-100">
                {userEmail}
              </span>
            </section>
            <footer className="mb-4 grid grid-flow-row-dense grid-cols-3 border border-b-0 border-r-0 border-l-0 border-gray-400 pr-5 pl-5 dark:border-white/20">
              <p className="col-span-2 mt-3 text-sm md:text-lg">
                La sesión expira {userSessionExpiresIn}
              </p>
              <button
                onClick={() => signOut()}
                className="ml-auto mt-3 flex items-center justify-center rounded-full hover:animate-bounce"
              >
                <ArrowLeftOnRectangleIcon className="hr-5 mr-1 h-6 w-6" />
              </button>
            </footer>
          </li>
        )}
      </main>
    </>
  );
}

export default AccountPage;
