import moment from "moment";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ContentLayout } from "../components/common/Layouts/ContentLayout";
import AccountScreen from "../components/screens/account/AccountScreen";

function AccountPage() {
  moment.locale("es");
  const router = useRouter();
  const { data: session, status } = useSession();

  useEffect(() => {
    if (status === "unauthenticated") {
      void router.push("/login");
    }
  }, [status]);
  return (
    <>
      <Head>
        <title>Comodo Stock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentLayout useContainer={true}>
        {session && <AccountScreen userData={session} />}
      </ContentLayout>
    </>
  );
}

export default AccountPage;
