import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Header } from "../components/common/Header/Header";
import ItemRender from "../components/common/Items/Results";
import { trpc } from "../utils/trpc";

function Home() {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const router = useRouter();
  const { data: session, status } = useSession();
  useEffect(() => {
    if (status === "unauthenticated") {
      void router.push("/login");
    }
  }, [status]);
  const stockItems = trpc.useQuery(["stock.getItems"]);
  const results = stockItems.data;
  console.log(session);
  return (
    <>
      <Head>
        <title>Comodo Stock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {results && <ItemRender results={results} />}
    </>
  );
}

export default Home;
