import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Input } from "react-daisyui";
import { Button, ButtonVariant } from "../components/common/Button/Button";
import { useForm } from "react-hook-form";
import { useEffect } from "react";

type RegisterForm = {
  username: string;
  password: string;
};

function LoginPage() {
  const router = useRouter();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterForm>();

  const onSubmit = async (data: RegisterForm) => {};

  const { data: session, status } = useSession();

  useEffect(() => {
    if (status === "authenticated") {
      void router.push("/");
    }
  }, [status]);
  return (
    <>
      <Head>
        <title>Comodo Stock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center gap-6 p-4">
        <h1 className="mb-5 text-5xl font-extrabold leading-normal text-gray-700 dark:text-gray-500 md:text-[5rem]">
          <span className="text-purple-300">Comodo</span> Stock
        </h1>
        <form
          className="flex w-2/3 flex-col gap-4 sm:w-1/3"
          onSubmit={handleSubmit(onSubmit)}
        >
          <Input
            id="username"
            className="w-full bg-gray-200 text-gray-700 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-300 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            placeholder="Username"
            {...register("username", { required: true })}
          />
          {errors.username && (
            <span className="text-red-500">This field is required</span>
          )}
          <Input
            id="password"
            className="w-full bg-gray-200 text-gray-700 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-300 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            placeholder="Password"
            {...register("password", { required: true })}
          />
          {errors.password && (
            <span className="text-red-500">This field is required</span>
          )}
          <Button type="submit" variant={ButtonVariant.Primary}>
            Iniciar
          </Button>
          <Button
            type="button"
            variant={ButtonVariant.Secondary}
            onClick={() => signIn("github", { callbackUrl: "/" })}
          >
            Iniciar con Github
          </Button>
        </form>
      </main>
    </>
  );
}

export default LoginPage;
