import moment from "moment";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ContentLayout } from "../components/common/Layouts/ContentLayout";
import ModifyScreen from "../components/screens/modify/ModifyScreen";
import { trpc } from "../utils/trpc";

function ModifyPage() {
  moment.locale("es");
  const router = useRouter();
  const { data: session, status } = useSession();
  const { id } = router.query;
  const stockItem = trpc.useQuery(["stock.getItem", { id: String(id) }]);
  const isNotLoading = !stockItem.isLoading;
  useEffect(() => {
    if (status === "unauthenticated") {
      void router.push("/login");
    }
  }, [status]);
  return (
    <>
      <Head>
        <title>Comodo Stock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentLayout useContainer={true}>
        {session && isNotLoading && (
          <ModifyScreen entity={stockItem.data!} authorId={session.user?.id!} />
        )}
      </ContentLayout>
    </>
  );
}

export default ModifyPage;
